### ISSUE TITLE
disabledDates refuses to work

### ISSUE THREAD

**Issue by JackWells** [TrevorS/bootstrap3-datetimepicker-rails#21]
I forked the jsfiddle, and it works ok here:
	http://jsfiddle.net/JackWells/dd49ys79/2/

I forked your git (the time-false demo) and it does *not* work:
	https://github.com/JackWells/bs3dp-test

What I did with the git:
1. Ran "rake rails:update:bin"
2. Ran "bundle install"
3. Changed app/assets/javascripts/test.js by copying exactly what is in the fiddle:

		$(function() {
		  $('#datetimepicker').datetimepicker({
		  pickTime: false,
		  defaultDate: "10/25/2014",
		  disabledDates: [
			  "10/27/2014 00:53",
			  "10/28/2014 00:53"
		  ]});
		});

The "pickTime: false" works.  The disabledDates does not.  Yet it works in the jsFiddle.  How can this be?

Edit: 
Took out '//= require bootstrap-datetimepicker' and put the 'bootstrap-datetimepicker.js ', referenced in the fiddle, in the tree.  No change.  

Added moment.js, referenced in the fiddle, to the js folder, removed require_tree, and manually required each js file, in order.  No change.

**Comment by TrevorS** [comment]
Updated to 4.0.0 will you check to see if you have similar issues and reopen if so?
