### ISSUE TITLE
Uncaught TypeError: undefined is not a function 

### ISSUE THREAD

**Issue by rnjailamba** [TrevorS/bootstrap3-datetimepicker-rails#25]
I was using :

$(function () {

                    $('#datetimepicker1').datetimepicker();

});

and was getting the error

The error was solved by using:

var j = jQuery.noConflict();

j(document).ready(function(){

                   j('#datetimepicker1').datetimepicker();

})

Is there any reason for this?

**Comment by rnjailamba** [comment]
I was using :
$(function () {
                    $('#datetimepicker1').datetimepicker();
});
and was getting the error

The error **j** was solved by using:
var j = jQuery.noConflict();
j(document).ready(function(){
        j('#datetimepicker1').datetimepicker();
})

Is there any reason for this?

**Comment by TrevorS** [comment]
Are you using any other Javascript libraries?  Can you reproduce it in a JSFiddle?

**Comment by rnjailamba** [comment]
Havent been able to reproduce,the other libraries are the following:
My application.js file includes the following:
//= require jquery
//= require jquery-ui
//= require jquery_ujs
//= require bootstrap
//= require turbolinks
//= require moment
//= require bootstrap-datetimepicker
//= require masonry/jquery.masonry
//= require_tree .

And below are all my script tags:
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
 <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&libraries=places&language=en-US"></script>

**Comment by rnjailamba** [comment]
Havent been able to reproduce the issue,the other libraries are the following:

**My application.js
file includes the following:**

//= require jquery

//= require jquery-ui

//= require jquery_ujs

//= require bootstrap

//= require turbolinks

//= require moment

//= require bootstrap-datetimepicker

//= require masonry/jquery.masonry

//= require_tree .

 

**And below are all my
script tags:**

&lt;script
src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"&gt;

 

&lt;script
src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"&gt;&lt;/script&gt;

  &lt;script
type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&libraries=places&language=en-US"&gt;&lt;/script&gt;

**Comment by rnjailamba** [comment]
Using 
(document).on('ready page:load', function () {


});
 
rather than

$(function () {

                    $('#datetimepicker1').datetimepicker();

});

**Comment by TrevorS** [comment]
Ok great, glad you were able to figure it out. :)
