### ISSUE TITLE
Value is not populated in the edit form when using data: {} on the text field

### ISSUE THREAD

**Issue by shaunpennell** [TrevorS/bootstrap3-datetimepicker-rails#26]
<%= f.text_field :due_date, class: 'form-control datetimepicker', data: { date_format: 'YYYY-MM-DD' } %>

If I use data: {date_format: 'YYYY-MM-DD'} to format the date it will allow me to insert into my MySQL database but I it doesn't populate the text field in my edit form.  The HTML src shows value for the element but doesn't show up in the render form itself.

If I remove data: {date_format: 'YYYY-MM-DD'} from the text field then the value does show up in the rendered text field BUT will not insert into my MySQL database because it is in the wrong format.

I'd like to be able to do the following but it doesn't work:

$(function () {
        $('.datetimepicker').datetimepicker({
            format: "yyyy-mm-dd"
        });
    });

**Comment by shaunpennell** [comment]
Never mind.  It was an issue with my date format initializer!

**Comment by TrevorS** [comment]
Glad you were able to figure it out.

**Comment by jkalavapudi** [comment]
I am having the same issue -- what did you do in your initializer?

**Comment by mattwr18** [comment]
We were having the same issue today and found this issue and then we realized that we were trying to format it as "DD/MM/YYYY" and then it wasn't populating the dates for us on the edit form. 
We were able to verify that only format "YYYY/MM/DD" works.
