### ISSUE TITLE
AM/PM button submits the form in Rails4 with jquery-ujs

### ISSUE THREAD

**Issue by sunderwood** [TrevorS/bootstrap3-datetimepicker-rails#29]
I'm using jquery-ujs which automatically submits a form when a button without the type='button' attribute is clicked. Please add this attribute to the toggle period button.

**Comment by TrevorS** [comment]
I suggest raising this issue at https://github.com/Eonasdan/bootstrap-datetimepicker.

When a new release occurs, I'll update the gem.

Thanks!
