### ISSUE TITLE
Picking Time

### ISSUE THREAD

**Issue by everaldo** [TrevorS/bootstrap3-datetimepicker-rails#3]
Hi!

I've installed your gem, but I'm facing some strange problems.

When I open the datetimepicker and click to select the time (hours), When I click in the button to select the previous our, another pop-up opens.

I'm attaching a photo of the behavior.

I'm using Rails 4.1.rc1

![datetimepicker](https://cloud.githubusercontent.com/assets/892012/2606900/802a577a-bb56-11e3-9bcd-ee9978dd208a.png)

**Comment by seanfcarroll** [comment]
@everaldo could you post an example of the simple_form code?

**Comment by everaldo** [comment]
Hello @seanfcarroll !

I'm sorry, but I don't have the code anymore. :(

Thanks for helping!
