### ISSUE TITLE
Can view value in the edit form

### ISSUE THREAD

**Issue by Frank004** [TrevorS/bootstrap3-datetimepicker-rails#30]
If I use the datepicker on the form in the edit part the value of the date field is empty and the datepicker is not selected with the value date form the database.
If need any more info let me know. thanx

**Comment by TrevorS** [comment]
I suggest raising this issue at https://github.com/Eonasdan/bootstrap-datetimepicker.

When a new release occurs, I'll update the gem.

Thanks!

**Comment by Frank004** [comment]
thank you

**Comment by khacluan** [comment]
:+1:

**Comment by thorn** [comment]
I've fixed this issue by setting format option on datepicker:

```
  $('.datetimepicker').datetimepicker({
    format: 'YYYY-MM-DD HH:mm'
  });
```

Here is what my input field html look like:

```
<input class="datetimepicker" type="text" value="2015-09-15 14:35:00 UTC" name="user[created_at]" id="user_created_at">
```

**Comment by pablougas** [comment]
I am currently having the same issue. Is there a fix or something that I am missing? I've tried thorn's workaround but I'd rather not force a value. 

`$(function () {
   $('#datetimepicker1').datetimepicker({
   });
});`

**Comment by pablougas** [comment]
Why is this issue marked as closed? Still doesn't work, even after setting the format.

**Comment by Frank004** [comment]
@pablougas check the https://github.com/Eonasdan/bootstrap-datetimepicker/issues/990
