### ISSUE TITLE
allowInputToggle option missing? 

### ISSUE THREAD

**Issue by jbhatab** [TrevorS/bootstrap3-datetimepicker-rails#31]
Went through the source code and couldn't find it. I definitely am looking for a way for the input to trigger it though. It is mentioned in the docs though as an option.

**Comment by LeeDumond** [comment]
Same here... it's in the docs but NOT in the source at all for v. 4.7.14

**Comment by jbhatab** [comment]
Yeah found out it says that it's only in the dev version. so you gotta just go to the dev branch.
