### ISSUE TITLE
unable to install 4.17.42 using bundler

### ISSUE THREAD

**Issue by klesse413** [TrevorS/bootstrap3-datetimepicker-rails#41]
I'm getting: `Could not find gem 'bootstrap3-datetimepicker-rails (~> 4.17.42)' in any of the gem sources listed in your Gemfile or available on this
machine.`
but 4.17.37 installs fine. Looking for .42 in hopes that I'll be able to get the date picker working using rails 5 simpleform, because as of now it doesn't show up using:

``` javascript
$( document ).on('turbolinks:load', function() {
  $('.form_datetime').datetimepicker({
    keepOpen: false,
    showTodayButton: true,
    format: 'yyyy-mm-dd'
  });
});
```

**Comment by klesse413** [comment]
@TrevorS

**Comment by TrevorS** [comment]
Sorry about that. Please try again -- I've updated the gem on RubyGems.

Thanks!
