### ISSUE TITLE
Calendar Css Broken

### ISSUE THREAD

**Issue by dahlia05** [TrevorS/bootstrap3-datetimepicker-rails#42]
![image](https://cloud.githubusercontent.com/assets/12134180/18412431/033ae88a-7786-11e6-9fc4-9e34cfc799a0.png)

Is there any suggestion, why the css is broken

This is has been used in following way 

<fieldset class="form fieldset-job_title">
            <%= f.label :validTill, :class => 'form-label' %>
            <div class="input-group date" id="datetimepicker1">
              <%= text_field :validTill, nil, class: 'form-control', data: { date_format: 'YYYY/MM/DD' }%>
              <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>        </span>
            </div>
            <%= @job_detail.errors[:validTill].join(", ") %>
          </fieldset>

**Comment by learn-to-program-easily** [comment]
What about looking at the z-index of your div, the one with "For Candidates"?

**Comment by dahlia05** [comment]
I have not set any z-index to any of the div element and apparently I am getting this issue on every where I am trying to use datepicker. 
![image](https://cloud.githubusercontent.com/assets/12134180/18816102/fdd7c736-8339-11e6-88d3-713c03d2f6ea.png)

**Comment by dahlia05** [comment]
Hey Sorry for disturbing you. The error was in the css of bootstrap datepicker css from
 https://github.com/Eonasdan/bootstrap-datetimepicker/

.bootstrap-datetimepicker-widget.dropdown-menu {
  margin: 2px 0;
  padding: 4px;
  width: 19em;
}

19em is too small and the other width was 39 em. So as i increase the width from 19 to 25. This got fixed,

Thanks a million for this gem. It is really a nice one.
