### ISSUE TITLE
background is transparent with Patternfly

### ISSUE THREAD

**Issue by kirantpatil** [TrevorS/bootstrap3-datetimepicker-rails#54]
Hi,

I am getting transparent datetime widget view when I try to access using patternfly. I could not take screenshot, since it disappears.

Let me know what needs to be done to see it in proper white background as shown in attached image.

#### application.scss file:

 @import "patternfly-sprockets";
  @import "patternfly";
  @import 'bootstrap-datetimepicker';

#### application.js file:
//= require jquery
//= require bootstrap
//= require patternfly
//= require bootstrap-datepicker
//= require moment
//= require bootstrap-datetimepicker

![screenshot from 2017-03-06 14 28 10](https://cloud.githubusercontent.com/assets/1178055/23603017/3d3a4e1c-0279-11e7-90eb-82b27c669a66.png)

**Comment by msands** [comment]
Not sure if this is the problem or not, but why do you have both `//= require bootstrap-datepicker` and `//=require bootstrap-datetimepicker`?

If you're using this gem, you should only need to add `//= require bootstrap-datetimepicker`

it's possible that you also need to add `@import "jquery-ui"` to the top of `application.scss`

**Comment by kirantpatil** [comment]
I will check it. Thanks.

**Comment by kirantpatil** [comment]
Sir your suggestion worked, I had to import jquery-ui. Thanks.
