### ISSUE TITLE
Problem with bootstrap 4.0 alpha 6

### ISSUE THREAD

**Issue by batamire** [TrevorS/bootstrap3-datetimepicker-rails#57]
Solved in: https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1996

CSS/SASS fix:
```
.fade
  &.in
    opacity: 1

.collapse
  &.in
    display: block
```

**Comment by William-H-M** [comment]
@batamire Hi, can you please close this as this has been solved as you said, thanks.
